W = import("modules/wingui.sl")
S = import("modules/sWidgets/core.sl")

theme = S.default_theme()
app = S.app({})

default_path = __dir + "/playground.sl"
window_ref = null
status_text = "Ready."
dirty = false

path_state = S.line_edit_state(default_path, {})
fn on_editor_change(text) {
    @dirty = true
    @status_text = "Edited."
    return null
}

editor_state = S.ide_editor_state(
    [
        "# ssiLang playground",
        "name = \"ssiLang\"",
        "",
        "fn greet(user) => \"hello, \" + user",
        "",
        "print(greet(name))",
        "",
        "sys."
    ].join("\n"),
    {
        on_change: on_editor_change
    }
)

fn redraw_now() {
    if @window_ref != null {
        @window_ref.redraw()
    }
    return null
}

fn set_status(text) {
    @status_text = text
    return null
}

fn mark_clean() {
    @dirty = false
    return null
}

fn new_file() {
    editor_state.set("")
    mark_clean()
    set_status("New file.")
    return null
}

fn load_file() {
    path = path_state.get()
    wrap = pcall(() -> sys.read_text(path))
    if not wrap.ok {
        set_status("Load failed: " + str(wrap.error))
        return null
    }
    editor_state.set(wrap.value)
    mark_clean()
    set_status("Loaded: " + path)
    return null
}

fn save_file() {
    path = path_state.get()
    wrap = pcall(() -> sys.write_text(path, editor_state.get()))
    if not wrap.ok {
        set_status("Save failed: " + str(wrap.error))
        return null
    }
    mark_clean()
    set_status("Saved: " + path)
    return null
}

fn load_demo() {
    editor_state.set(
        [
            "# Demo script generated by SLCreator",
            "nums = [1, 2, 3, 4, 5]",
            "picked = nums |> filter($ % 2 == 1) |> map($ * 10)",
            "print(picked)",
            "",
            "fn fact(n) {",
            "    ans = 1",
            "    for i in range(1, n + 1) {",
            "        ans = ans * i",
            "    }",
            "    return ans",
            "}",
            "",
            "print(fact(6))"
        ].join("\n")
    )
    mark_clean()
    set_status("Loaded demo.")
    return null
}

fn run_script() {
    save_file()
    redraw_now()

    exe = __dir + "/sl.exe"
    path = path_state.get()

    set_status("Running: " + path)
    redraw_now()

    wrap = pcall(() -> sys.spawn([exe, path], {cwd: __dir, detached: false}))
    if not wrap.ok {
        set_status("Run failed: " + str(wrap.error))
        return null
    }

    code = wrap.value.wait()
    set_status("Process exited with code " + str(code))
    return null
}

fn make_action_button(text, width, action) {
    b = S.button(text, action, {})
    b.width = width
    return b
}

fn status_widget() {
    fn measure_status(ctx, avail_w) {
        return {w: avail_w, h: 56}
    }

    fn layout_status(ctx, box) {
        path = path_state.get()
        line_col = editor_state.line_col()
        file_name = path.split("/")[len(path.split("/")) - 1]
        dirty_text = dirty => "modified" || "saved"
        completion_text = editor_state.completion_active() => "  |  Suggest " + str(len(editor_state.completion_items())) + ": " + editor_state.completion_summary() || ""
        return [
            W.fill_rect(box.x, box.y, box.w, box.h, theme.panel_bg),
            W.rect(box.x, box.y, box.w, box.h, theme.panel_border, 1),
            W.text(box.x + 14, box.y + 10, "Status: " + status_text, {
                color: theme.text,
                font: theme.font
            }),
            W.text(box.x + 14, box.y + 30, "File: " + file_name + "  |  " + dirty_text + "  |  Ln " + str(line_col.line + 1) + ", Col " + str(line_col.col + 1) + completion_text, {
                color: theme.muted_text,
                font: W.font("Segoe UI", 14)
            })
        ]
    }

    return S.custom({
        measure: measure_status,
        layout: layout_status
    })
}

fn hint_panel() {
    return S.box(
        S.column([
            S.label("SLCreator", {
                font: theme.title_font
            }),
            S.label("A pure-sL IDE shell built on sWidgets.", {
                color: theme.muted_text
            }),
            S.divider({}),
            S.label("IDE Features", {
                font: W.font("Segoe UI", 15, {weight: 700})
            }),
            S.label("1. Syntax highlight for ssiLang", {
                color: theme.text
            }),
            S.label("2. Ctrl+Space or '.' to trigger completion", {
                color: theme.text
            }),
            S.label("3. Tab / Enter accept completion, Enter auto-indent", {
                color: theme.text
            }),
            S.label("4. Load / Save / Run with sl.exe", {
                color: theme.text
            })
        ], {
            spacing: 8,
            padding: 14
        }),
        {
            bg: theme.panel_bg,
            border: theme.panel_border
        }
    )
}

fn root_widget() {
    path_edit = S.line_edit(path_state, {
        placeholder: "script path"
    })
    path_edit.flex = 1

    toolbar = S.row([
        path_edit,
        make_action_button("Load", 70, load_file),
        make_action_button("Save", 70, save_file),
        make_action_button("Run", 70, run_script),
        make_action_button("Demo", 76, load_demo),
        make_action_button("New", 68, new_file)
    ], {
        spacing: 8,
        align_y: "center"
    })

    editor_box = S.ide_editor(editor_state, {})
    editor_box.flex = 1

    return S.column([
        hint_panel(),
        toolbar,
        editor_box,
        status_widget()
    ], {
        spacing: 12,
        padding: 14
    })
}

window_ref = app.create_window({
    title: "SLCreator IDE",
    width: 960,
    height: 760,
    visible: true,
    root: root_widget()
})

app.run()
